/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Entity_DESTool */

#ifndef _Included_Entity_DESTool
#define _Included_Entity_DESTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Entity_DESTool
 * Method:    do_encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Entity_DESTool_do_1encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Entity_DESTool
 * Method:    do_decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Entity_DESTool_do_1decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
